const { WAConnection } = require("@adiwajshing/baileys")
const chalk = require('chalk')
const fs = require("fs")
const exec = require('child_process')

const ratchel330 = new WAConnection()
exports.ratchel330 = ratchel330

exports.connect = async() => {
    ratchel330.version = [2, 2143, 3]
    console.log(chalk.keyword("aqua")('◦ Conectando ◦'))
    let auth = './ratchel330.json'
    ratchel330.logger.level = 'warn'
    ratchel330.on("qr", () => {
        console.log(chalk.keyword("yellow")('💎   Escanea el codigo...'))
    })
    fs.existsSync(auth) && ratchel330.loadAuthInfo(auth)
    ratchel330.on('connecting', () => {
        console.log(chalk.whiteBright("⌛"), chalk.keyword("red")("estado de Ratchel🏴‍☠️"), chalk.keyword("aqua")("Connecting..."))
    })
        ratchel330.on('open', () => {

       console.log(chalk.keyword("red")("│"), chalk.keyword("red") ("´´´´´´´´´´´´´´´´´´´´´´´¶´´´´´´´´´¶´´´´´´´´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´´´´´´´´´¶´´´´´´´´´¶´´´´´´´´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´´´´´¶´´´¶´´´´´´´´´¶´´´¶´´´´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´´´´´¶´´¶¶´´´´´´´´´¶¶´´¶´´´´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´´´´´¶¶´¶¶¶´´´´´´´¶¶¶´¶¶´´´´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´¶´´´´´´¶¶´´´¶¶¶´´´´´¶¶¶´´´¶¶´´´´´´¶´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´¶¶´´´´´´¶¶´´´¶¶¶´´´´´¶¶¶´´´¶¶´´´´´´¶¶´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´¶¶´´´´´´¶¶´´´´¶¶¶¶´´´¶¶¶¶´´´´¶¶´´´´´´¶¶´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´¶¶´´´´´¶¶¶´´´´¶¶¶¶´´¶¶¶¶¶´´´´¶¶¶´´´´´¶¶¶´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´¶´´¶¶¶´´´´¶¶¶¶´´´´¶¶¶¶´´´¶¶¶¶´´´´¶¶¶¶´´´¶¶¶¶´´¶´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´¶¶´¶¶¶¶¶´´¶¶¶¶´´´¶¶¶¶¶´´´¶¶¶¶¶´´´¶¶¶¶´´¶¶¶¶¶´¶¶´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´¶¶´¶¶¶¶¶´´¶¶¶¶¶¶¶¶¶¶¶´´´´´¶¶¶¶¶¶¶¶¶¶¶´´¶¶¶¶¶´¶¶´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´¶¶´¶¶¶¶¶´´¶¶¶¶¶¶¶¶¶¶¶´´´´´¶¶¶¶¶¶¶¶¶¶¶´´¶¶¶¶¶´¶¶´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´¶¶¶´´¶¶¶¶´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´¶¶¶¶´´¶¶¶´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´¶¶¶¶´´¶¶¶¶´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´¶¶¶¶´´¶¶¶¶´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´¶¶¶¶´´´¶¶¶¶¶´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´¶¶¶¶¶´´´¶¶¶¶´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´¶¶¶¶´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´¶¶¶¶´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´¶¶¶¶¶´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´¶¶¶¶´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")(" ´´´ ¶¶¶¶¶´´´´´´´´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´´´´´´´´´¶¶¶¶¶´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´¶¶¶¶¶¶´´´´´´´´´´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶´´´´´´´´´´´´´¶¶¶¶¶¶´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´¶¶¶¶¶¶¶´´´´´´´:::´´´¶¶¶¶¶¶¶¶¶´´´´:::´´´ ´´¶¶¶¶¶¶´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´¶¶¶¶¶¶¶¶´´´´´´´´´´´´´¶¶¶¶¶´´´´´´´´´´´´´¶¶¶¶¶¶¶¶´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´¶¶¶¶¶¶¶¶¶¶´´´´´´´´´´´¶¶¶´´´´´´´´´´´¶¶¶¶¶¶¶¶¶¶´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´´¶¶¶¶¶¶¶¶¶¶´´´´´¶¶¶¶¶¶¶¶¶¶´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´´´¶¶¶¶¶¶¶¶´´´´´´´¶¶¶¶¶¶¶¶´´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´´¶¶¶¶¶¶¶¶¶´´´´´´´¶¶¶¶¶¶¶¶¶´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´´¶¶¶¶¶¶¶¶¶´¶¶¶¶¶´¶¶¶¶¶¶¶¶¶´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´¶¶¶´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´¶¶¶´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´¶¶´´¶¶¶¶´´¶¶¶¶¶´´¶¶¶¶´´¶¶´´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("│"), chalk.keyword("red")("´´´´´´´´´´´´´´´´´´´´´¶¶¶¶´´¶¶¶¶¶´´¶¶¶¶´´´´´´´´´´´´´´´´´´´´"))
       console.log(chalk.keyword("red")("├---------------------------------------------------------------"))
       console.log(chalk.keyword("red")('│'), chalk.keyword("blue")('⌈ '), chalk.keyword("aqua")('CONECTADO'), chalk.keyword("blue")(' ⌉'),
        chalk.keyword("green")(' ═══'))
        console.log(chalk.keyword("red")("├"), chalk.keyword("aqua")("WA Version : "), chalk.whiteBright(ratchel330.user.phone.wa_version))
        console.log(chalk.keyword("red")("├"), chalk.keyword("aqua")("OS Version : "), chalk.whiteBright(ratchel330.user.phone.os_version))
        console.log(chalk.keyword("red")("├"), chalk.keyword("aqua")("Device : "), chalk.whiteBright(ratchel330.user.phone.device_manufacturer))
        console.log(chalk.keyword("red")("├"), chalk.keyword("aqua")("Model : "), chalk.whiteBright(ratchel330.user.phone.device_model))
        console.log(chalk.keyword("red")("├"), chalk.keyword("aqua")("OS Build Number : "), chalk.whiteBright(ratchel330.user.phone.os_build_number))
        console.log(chalk.keyword("red")("│"), chalk.keyword("red")('╭╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╮'))
        console.log(chalk.keyword("red")("│"), chalk.keyword("red")('│'), chalk.keyword("yellow")('       BIENVENIDO'))
        console.log(chalk.keyword("red")("│"), chalk.keyword("red")('│'), chalk.keyword("aqua")(' Creditos:'))
        console.log(chalk.keyword("red")("│"), chalk.keyword("red")('│'), chalk.keyword("magenta")('hunter dexter | ☣️ℜ𝔞𝔱𝔠𝔥𝔢𝔩☣️'))
        console.log(chalk.keyword("red")("│"), chalk.keyword("red")('╰╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╯'))
        console.log(chalk.keyword("red")("├---------------------------------------------------------------"))
        const authInfo = ratchel330.base64EncodedAuthInfo()
        fs.writeFileSync(auth, JSON.stringify(authInfo, null, '\t'))
    })
    await ratchel330.connect({ timeoutMs: 30 * 1000 })
    return ratchel330
}
